"""add cache token columns to agent_runs

Revision ID: 3cc32e5342bd
Revises: c43925d02655
Create Date: 2026-09-19 14:14:39.994825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc32e5342bd'
down_revision: Union[str, Sequence[str], None] = 'c43925d02655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('cache_read_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('cache_write_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'cache_write_tokens')
    op.drop_column('agent_runs', 'cache_read_tokens')
    # ### end Alembic commands ###
