"""add kind column to agent_runs

Revision ID: c43925d02655
Revises: 0ef692aa42a3
Create Date: 2026-09-17 14:22:31.587832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43925d02655'
down_revision: Union[str, Sequence[str], None] = '0ef692aa42a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('kind', sa.Text(), server_default='score_fit', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'kind')
    # ### end Alembic commands ###
